### ISSUE TITLE
【table】Not displayed from the middle when tableContent too long size table

### ISSUE THREAD

**Issue by yoshixmk** [JasonHughes94/deno-markdown#1]
In ranking_result.tsv I can see that the result exists, but when I tried to use this Markdown library and tried to output, I had a problem.  
See the README.md (table output result) for the url below
https://github.com/yoshixmk/deno-x-ranking/tree/master/examples

Ex: Bellow the tableContent. [Details code, this](https://github.com/yoshixmk/deno-x-ranking/blob/master/generateMarkdownFile.ts#L16-L38)
```typescript
const tableContent: Array<Array<string>>() = /* too long contents */;
new Markdown()
  .table(
    tableContent,
  )
  .write("./examples/", "README");
```

**Comment by JasonHughes94** [comment]
Hey @yoshixmk Just trying to get an understanding of your problem.

Are you expecting more rows from the table output result in the README.md or is it in regards to the scrolling on the README preview?

The code you have supplied is correct and should be working.

**Comment by yoshixmk** [comment]
@JasonHughes94 Thank you for contacting me.  
All 629 lines, but 29 lines. (headless 27 lines)
<img width="1274" alt="cut_off_lines" src="https://user-images.githubusercontent.com/6196702/85919703-c3f74480-b8a8-11ea-8743-fb75246801db.png">
The full text you want to output is below.  
https://github.com/yoshixmk/deno-x-ranking/blob/master/examples/ranking_result.tsv#L27

**Comment by JasonHughes94** [comment]
Hey @yoshixmk,

I've managed to recreate the bug locally.
Looks like it gets cut off after a certain character limit.

The bug was with the writing of the file you can take a look here - https://github.com/JasonHughes94/deno-markdown/commit/fb183e6b85fcc50957e62d58cd85a13c3826ea43

I've just pushed a commit that should fix this issue.

**Comment by yoshixmk** [comment]
@JasonHughes94  Thank you very much.
Again, I tried the output again and it seems to be okay!!
I was convinced about the cause. I will continue to support this repository

**Comment by JasonHughes94** [comment]
@yoshixmk No problem at all!

Thank you for using the repository.
If you need anymore help just put in some more issues
